name: Deploy ASP.NET Core to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama donde tienes tu código

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Asegúrate de usar la versión correcta

      - name: Publicar la app como estática
        run: dotnet publish -c Release -o dist --nologo

      - name: Configurar GitHub Pages
         uses: actions/setup-dotnet@v1
        with:
          path: dist/wwwroot  # Asegúrate de que este sea el directorio de salida correcto

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Desplegar en GitHub Pages
        uses: actions/deploy-pages@v2
