name: Deploy ASP.NET Core to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama donde tienes tu código

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Ajusta la versión según tu proyecto

      - name: Publicar la app como estática
        run: dotnet publish -c Release -o dist --nologo

      - name: Subir artefacto para GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist/wwwroot  # Asegúrate de que sea el directorio correcto

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./public

      - name: Desplegar en GitHub Pages
        uses: actions/deploy-pages@v2

